Repository wecode-bootcamp-korea/13-BeautyOfFunction-frontend, pull requests merged in 2020-11, with the labels that each got.

#4 [13기 김보경] Add: Login Page 소셜로그인 기능 추가
  package-lock.json
  package.json
  public/index.html
  src/pages/Login/Login.js
  src/pages/Signup/Signup.js
Labels: Status: 수정 요청

#3 [13기 김정현] Add: MainPage 완료
  package-lock.json
  package.json
  public/images/MainLogo.png
  public/images/arrowdown.png
  public/images/comb.svg
  public/images/facebook.svg
  public/images/footerKorea.png
  public/images/instagram.svg
  public/images/left-arrow.svg
  public/images/list1.jpg
  public/images/mainFirst.jpg
  public/images/mainFour.png
  public/images/mainFourText.png
  public/images/mainSecond2.png
  public/images/pinterest.svg
  public/images/right-arrow.svg
  public/images/sixImg1.png
  public/images/sixImg2.png
  public/images/sixImg3.png
  public/images/sixImg4.png
  public/images/sixImg5.png
  public/images/step1.jpg
  public/images/step2.jpg
  public/images/step3.jpg
  public/images/twitter.svg
  public/images/youtube.svg
  public/index.html
  src/Routes.js
  src/pages/Mainpage/Hairlist.js
  src/pages/Mainpage/MainFirst.js
  src/pages/Mainpage/MainFive.js
  src/pages/Mainpage/MainFooter.js
  src/pages/Mainpage/MainFour.js
  src/pages/Mainpage/MainSecond.js
  src/pages/Mainpage/MainSix.js
  src/pages/Mainpage/MainThree.js
  src/pages/Mainpage/Main_banner2.png
  src/pages/Mainpage/Mainpage.js
  src/pages/Mainpage/Mainpage.scss
  src/pages/Mainpage/mainSecond.png
  src/pages/Mainpage/mainSix.jpg
  src/pages/Signup/Signup.js
Labels: Status: 리뷰 요청

#2 [13기 임수현] Refactoring: 멘토리뷰 반영
  package-lock.json
  package.json
  public/Data/DetailpageData.json
  public/Images/left-removebg-preview.png
  public/Images/right-removebg-preview.png
  src/pages/Detailpage/Components/BadgesComponent.js
  src/pages/Detailpage/Components/DetailPageReviewSectionComponent.js
  src/pages/Detailpage/Components/GreatforComponent.js
  src/pages/Detailpage/Components/IngredientsComponent.js
  src/pages/Detailpage/Components/RecommendedComponent.js
  src/pages/Detailpage/Components/StyledSectionComponent.js
  src/pages/Detailpage/Components/theme.js
  src/pages/Detailpage/Detailpage.js
Labels: Status: 리뷰 진행중

#5 [13기 이지영] Add: 레이아웃 완성
  package-lock.json
  package.json
  public/Images/blue.png
  public/Images/bluegray.png
  public/Images/mint.png
  public/Images/orange.png
  public/Images/pink.png
  public/Images/purple.png
  public/Images/star_rating.png
  public/Images/star_rating2.png
  public/Images/violet.png
  public/Images/white.png
  public/Images/yellow.png
  src/Routes.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Reviewpage/Reviewpage.js
  src/pages/Reviewpage/Reviewpage.scss
  src/pages/Reviewpage/ReviewpageData.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#7 [13기 김정현] Fix: 공통 Nav/Footer 리팩토링 완료
  public/images/MainLogo.png
  public/images/MainLogoNF.png
  src/Routes.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: Status: 리뷰 요청

#6 [13기 임수현] Fix: Conflict 해결
  package-lock.json
  package.json
  public/Data/QuizData.json
  public/Images/Detail_color/Detail_blue1.png
  public/Images/Detail_color/Detail_blue2.png
  public/Images/Detail_color/Detail_gray1.png
  public/Images/Detail_color/Detail_gray2.png
  public/Images/Detail_color/Detail_mint1.png
  public/Images/Detail_color/Detail_mint2.png
  public/Images/Detail_color/Detail_orange1.png
  public/Images/Detail_color/Detail_orange2.png
  public/Images/Detail_color/Detail_pink1.png
  public/Images/Detail_color/Detail_pink2.png
  public/Images/Detail_color/Detail_purple1.png
  public/Images/Detail_color/Detail_purple2.png
  public/Images/Detail_color/Detail_violet1.png
  public/Images/Detail_color/Detail_violet2.png
  public/Images/Detail_color/Detail_white1.png
  public/Images/Detail_color/Detail_white2.png
  public/Images/Detail_color/Detail_yellow1.png
  public/Images/Detail_color/Detail_yellow2.png
  public/Images/Detail_color/Main_banner.png
  public/Images/Detail_color/nonbackground/Detail_blue1-removebg-preview.png
  public/Images/Detail_color/nonbackground/Detail_gray1-removebg-preview.png
  public/Images/Detail_color/nonbackground/Detail_mint1-removebg-preview.png
  public/Images/Detail_color/nonbackground/Detail_orange1-removebg-preview.png
  public/Images/Detail_color/nonbackground/Detail_pink1-removebg-preview.png
  public/Images/Detail_color/nonbackground/Detail_purple1-removebg-preview.png
  public/Images/Detail_color/nonbackground/Detail_violet1-removebg-preview.png
  public/Images/Detail_color/nonbackground/Detail_white1-removebg-preview.png
  public/Images/Detail_color/nonbackground/Detail_yellow1-removebg-preview.png
  src/Routes.js
  src/pages/Quiz/Component/QuizFirstPage.js
  src/pages/Quiz/Component/QuizFourthPage.js
  src/pages/Quiz/Component/QuizSecondPage.js
  src/pages/Quiz/Component/QuizThirdPage.js
  src/pages/Quiz/Component/subComponent/InputComponent.js
  src/pages/Quiz/Component/subComponent/theme.js
  src/pages/Quiz/Component/svgComponents/coarse.js
  src/pages/Quiz/Component/svgComponents/coily.js
  src/pages/Quiz/Component/svgComponents/curly.js
  src/pages/Quiz/Component/svgComponents/dry.js
  src/pages/Quiz/Component/svgComponents/fine.js
  src/pages/Quiz/Component/svgComponents/medium.js
  src/pages/Quiz/Component/svgComponents/normal.js
  src/pages/Quiz/Component/svgComponents/oily.js
  src/pages/Quiz/Component/svgComponents/straight.js
  src/pages/Quiz/Component/svgComponents/wavy.js
  src/pages/Quiz/Quiz.js
Labels: Status: 리뷰 요청

#9 [13기 이지영] Feature/cart 레이아웃 완성
  package-lock.json
  package.json
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Reviewpage/Reviewpage.js
  src/pages/Reviewpage/ReviewpageData.js
Labels: Status: Accepted

#10 [13기 임수현]Add: 백엔드 데이터 연동
  src/pages/Detailpage/Components/DetailPageReviewSectionComponent.js
  src/pages/Detailpage/Detailpage.js
Labels: Status: Accepted

#11 [13기 이지영] 장바구니 최종본
  public/Images/cartImage.png
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
Labels: Status: 리뷰 요청
